"""Install and render the versioned local Vibe Memory macOS runtime."""

from __future__ import annotations

import ctypes
import json
import os
import pathlib
import plistlib
import re
import shutil
import stat
import subprocess
from string import Template
import sys
from typing import Any, Callable
import uuid
from xml.sax.saxutils import escape

from vibe_memory_paths import RuntimePaths


_PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
_LAUNCH_AGENT_TEMPLATE = _PROJECT_ROOT / "templates/macos/com.noema.vibe-memory.plist"
_REQUIRED_DIRECTORIES = ("scripts", "templates", "docs")
_REQUIRED_FILES = ("README.md", "release.json")
_OPTIONAL_FILES = ("LICENSE",)
_SEMVER_IDENTIFIER = r"(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)"
_VERSION_PATTERN = re.compile(
    r"^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)"
    rf"(?:-({_SEMVER_IDENTIFIER}(?:\.{_SEMVER_IDENTIFIER})*))?"
    r"(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$"
)
_PYTHON_VERSION_PATTERN = re.compile(r"^[0-9]+\.[0-9]+$")
MINIMUM_PYTHON = (3, 10)
LAUNCHER_MARKER = "# Vibe Memory stable launcher; generated by the installer."
RENAME_EXCL = 0x00000004
_DIRECTORY_OPEN_FLAGS = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
_TRUSTED_SYSTEM_ALIASES = {
    pathlib.Path("/etc"): pathlib.Path("/private/etc"),
    pathlib.Path("/tmp"): pathlib.Path("/private/tmp"),
    pathlib.Path("/var"): pathlib.Path("/private/var"),
}


class _AnchoredPath:
    """A display path paired with a directory-fd-relative entry name."""

    def __init__(
        self,
        parent_fd: int,
        entry_name: str,
        display_path: pathlib.Path,
        directory_fd: int | None = None,
    ) -> None:
        self.parent_fd = parent_fd
        self.entry_name = entry_name
        self.display_path = display_path
        self.directory_fd = directory_fd
        self.creation_ledger: dict[str, tuple[int, int, int]] = {}

    @property
    def name(self) -> str:
        return self.entry_name

    def __fspath__(self) -> str:
        return str(self.display_path)

    def __str__(self) -> str:
        return str(self.display_path)

    def __truediv__(self, child: str) -> pathlib.Path:
        return self.display_path / child


class TemporaryCleanupConflict(RuntimeError):
    """Raised when a temporary install entry no longer has its created identity."""


class InstallError(RuntimeError):
    """Raised when an install lifecycle operation safely refuses to continue."""


def probe_python(executable: str) -> tuple[int, int] | None:
    """Return the candidate interpreter's major/minor version without a shell."""
    try:
        completed = subprocess.run(
            [executable, "-c", "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')"],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if completed.returncode != 0:
        return None
    match = re.fullmatch(r"([0-9]+)\.([0-9]+)\s*", completed.stdout)
    if match is None:
        return None
    return int(match.group(1)), int(match.group(2))


def validate_python(
    executable: str | os.PathLike[str],
    probe: Callable[[str], tuple[int, int] | None] = probe_python,
) -> str:
    """Validate and canonicalize a persisted Python 3.10+ interpreter path."""
    if not isinstance(executable, (str, os.PathLike)):
        raise InstallError("Python 3.10 or newer is required")
    candidate = os.path.abspath(os.path.expanduser(os.fspath(executable)))
    version = probe(candidate)
    if (
        not isinstance(version, tuple)
        or len(version) != 2
        or any(isinstance(item, bool) or not isinstance(item, int) for item in version)
        or version < MINIMUM_PYTHON
    ):
        raise InstallError("Python 3.10 or newer is required")
    return candidate


def discover_python(
    probe: Callable[[str], tuple[int, int] | None] = probe_python,
) -> str:
    """Select the first available Python interpreter meeting the release minimum."""
    configured = os.environ.get("VIBE_MEMORY_PYTHON")
    candidates = (
        configured,
        shutil.which("python3"),
        "/opt/homebrew/bin/python3",
        "/usr/local/bin/python3",
        "/usr/bin/python3",
    )
    for candidate in candidates:
        if not candidate:
            continue
        try:
            return validate_python(candidate, probe)
        except InstallError:
            continue
    raise InstallError("Python 3.10 or newer was not found")


def _validate_manifest(manifest: dict[str, Any]) -> str:
    required = {
        "app_version",
        "data_schema_version",
        "hook_protocol_version",
        "minimum_python",
        "platform",
    }
    missing = required.difference(manifest)
    if missing:
        raise ValueError(f"release manifest missing required fields: {', '.join(sorted(missing))}")
    version = manifest["app_version"]
    if not isinstance(version, str) or not _VERSION_PATTERN.fullmatch(version):
        raise ValueError("release app_version must be a semantic version")
    for field in ("data_schema_version", "hook_protocol_version"):
        value = manifest[field]
        if isinstance(value, bool) or not isinstance(value, int) or value < 1:
            raise ValueError(f"release {field} must be a positive integer")
    minimum_python = manifest["minimum_python"]
    if not isinstance(minimum_python, str) or not _PYTHON_VERSION_PATTERN.fullmatch(minimum_python):
        raise ValueError("release minimum_python must use major.minor format")
    if manifest["platform"] != "macOS":
        raise ValueError("release platform must be macOS")
    return version


def _identity(metadata: os.stat_result) -> tuple[int, int]:
    return metadata.st_dev, metadata.st_ino


def _read_regular_file_at(parent_fd: int, name: str, display_path: pathlib.Path) -> bytes:
    try:
        before = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
    except OSError as error:
        raise ValueError(f"required release file is missing: {display_path}") from error
    if not stat.S_ISREG(before.st_mode):
        raise ValueError(f"release source must contain regular files only: {display_path}")
    try:
        descriptor = os.open(
            name,
            os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
            dir_fd=parent_fd,
        )
    except OSError as error:
        raise ValueError(f"unsafe release source file: {display_path}") from error
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode) or _identity(opened) != _identity(before):
            raise ValueError(f"release source file changed while opening: {display_path}")
        with os.fdopen(descriptor, "rb", closefd=False) as handle:
            return handle.read()
    finally:
        os.close(descriptor)


def _open_source_directory_at(parent_fd: int, name: str, display_path: pathlib.Path) -> int:
    try:
        before = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
    except OSError as error:
        raise ValueError(f"required release directory is missing: {display_path}") from error
    if not stat.S_ISDIR(before.st_mode):
        raise ValueError(f"release source must contain real directories only: {display_path}")
    try:
        descriptor = os.open(name, _DIRECTORY_OPEN_FLAGS, dir_fd=parent_fd)
    except OSError as error:
        raise ValueError(f"unsafe release source directory: {display_path}") from error
    try:
        opened = os.fstat(descriptor)
    except Exception:
        os.close(descriptor)
        raise
    if not stat.S_ISDIR(opened.st_mode) or _identity(opened) != _identity(before):
        os.close(descriptor)
        raise ValueError(f"release source directory changed while opening: {display_path}")
    return descriptor


def _snapshot_directory_fd(
    directory_fd: int,
    display_root: pathlib.Path,
    prefix: pathlib.Path,
) -> dict[str, tuple[str, bytes | None]]:
    entries: dict[str, tuple[str, bytes | None]] = {}
    for name in os.listdir(directory_fd):
        relative = prefix / name
        display_path = display_root / relative
        try:
            metadata = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        except OSError as error:
            raise ValueError(f"release source changed during enumeration: {display_path}") from error
        if stat.S_ISDIR(metadata.st_mode):
            child_fd = _open_source_directory_at(directory_fd, name, display_path)
            try:
                entries[str(relative)] = ("directory", None)
                entries.update(_snapshot_directory_fd(child_fd, display_root, relative))
            finally:
                os.close(child_fd)
        elif stat.S_ISREG(metadata.st_mode):
            entries[str(relative)] = (
                "file",
                _read_regular_file_at(directory_fd, name, display_path),
            )
        else:
            raise ValueError(f"release source must contain regular files only: {display_path}")
    return entries


def _snapshot_source_release(
    source_root: pathlib.Path,
) -> dict[str, tuple[str, bytes | None]]:
    try:
        before = os.lstat(source_root)
    except OSError as error:
        raise ValueError("release source root must be a real directory") from error
    if not stat.S_ISDIR(before.st_mode):
        raise ValueError("release source root must be a real directory")
    try:
        source_fd = os.open(source_root, _DIRECTORY_OPEN_FLAGS)
    except OSError as error:
        raise ValueError("release source root must be a real directory") from error
    try:
        opened = os.fstat(source_fd)
        if not stat.S_ISDIR(opened.st_mode) or _identity(opened) != _identity(before):
            raise ValueError("release source root changed while opening")
        entries: dict[str, tuple[str, bytes | None]] = {}
        for name in _REQUIRED_DIRECTORIES:
            display_path = source_root / name
            child_fd = _open_source_directory_at(source_fd, name, display_path)
            try:
                entries[name] = ("directory", None)
                entries.update(_snapshot_directory_fd(child_fd, source_root, pathlib.Path(name)))
            finally:
                os.close(child_fd)
        for name in _REQUIRED_FILES:
            entries[name] = (
                "file",
                _read_regular_file_at(source_fd, name, source_root / name),
            )
        for name in _OPTIONAL_FILES:
            try:
                os.stat(name, dir_fd=source_fd, follow_symlinks=False)
            except FileNotFoundError:
                continue
            except OSError as error:
                raise ValueError(f"unsafe optional release file: {source_root / name}") from error
            entries[name] = (
                "file",
                _read_regular_file_at(source_fd, name, source_root / name),
            )
        return entries
    finally:
        os.close(source_fd)


def _validate_install_ancestor_chain(path: pathlib.Path) -> None:
    """Reject unsafe components, allowing only exact macOS canonical aliases."""
    absolute = path.absolute()
    current = pathlib.Path(absolute.anchor)
    for component in absolute.parts[1:]:
        current /= component
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            break
        if stat.S_ISLNK(metadata.st_mode):
            expected = _TRUSTED_SYSTEM_ALIASES.get(current)
            if expected is None or metadata.st_uid != 0:
                raise ValueError(f"untrusted symlink in install path: {current}")
            try:
                resolved = current.resolve(strict=True)
            except (OSError, RuntimeError) as error:
                raise ValueError(f"broken system alias in install path: {current}") from error
            if resolved != expected or not resolved.is_dir():
                raise ValueError(f"system alias target is not trusted: {current}")
        elif not stat.S_ISDIR(metadata.st_mode):
            raise ValueError(f"non-directory in install path: {current}")


def _canonical_install_path(path: pathlib.Path) -> pathlib.Path:
    absolute = path.absolute()
    for alias, target in _TRUSTED_SYSTEM_ALIASES.items():
        try:
            suffix = absolute.relative_to(alias)
        except ValueError:
            continue
        return target / suffix
    return absolute


def _open_or_create_directory_chain(path: pathlib.Path) -> int:
    descriptor = os.open(path.anchor, _DIRECTORY_OPEN_FLAGS)
    try:
        for component in path.parts[1:]:
            try:
                child = os.open(component, _DIRECTORY_OPEN_FLAGS, dir_fd=descriptor)
            except FileNotFoundError:
                try:
                    os.mkdir(component, 0o700, dir_fd=descriptor)
                except FileExistsError:
                    pass
                try:
                    child = os.open(component, _DIRECTORY_OPEN_FLAGS, dir_fd=descriptor)
                except OSError as error:
                    raise ValueError(f"unsafe install path component: {component}") from error
            except OSError as error:
                raise ValueError(f"unsafe install path component: {component}") from error
            os.close(descriptor)
            descriptor = child
        return descriptor
    except Exception:
        os.close(descriptor)
        raise


def _open_install_layout(paths: RuntimePaths) -> tuple[pathlib.Path, int, pathlib.Path, int]:
    requested = pathlib.Path(paths.install_root)
    _validate_install_ancestor_chain(requested)
    install_root = _canonical_install_path(requested)
    install_fd = _open_or_create_directory_chain(install_root)
    try:
        os.fchmod(install_fd, 0o700)
        try:
            os.mkdir("releases", 0o700, dir_fd=install_fd)
        except FileExistsError:
            pass
        try:
            releases_fd = os.open("releases", _DIRECTORY_OPEN_FLAGS, dir_fd=install_fd)
        except OSError as error:
            raise ValueError("unsafe releases directory") from error
        try:
            os.fchmod(releases_fd, 0o700)
        except Exception:
            os.close(releases_fd)
            raise
    except Exception:
        os.close(install_fd)
        raise
    return install_root, install_fd, install_root / "releases", releases_fd


def _darwin_rename(
    source: pathlib.Path | str,
    destination: pathlib.Path | str,
    flags: int,
) -> None:
    """Invoke Darwin's flagged atomic rename and preserve its errno."""
    if sys.platform != "darwin":
        raise NotImplementedError("flagged atomic rename is only supported on Darwin")
    libc = ctypes.CDLL(None, use_errno=True)
    renamex_np = libc.renamex_np
    renamex_np.argtypes = (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_uint)
    renamex_np.restype = ctypes.c_int
    result = renamex_np(os.fsencode(source), os.fsencode(destination), flags)
    if result != 0:
        error_number = ctypes.get_errno()
        raise OSError(
            error_number,
            os.strerror(error_number),
            str(source),
            str(destination),
        )


def _darwin_renameat(
    source_parent_fd: int,
    source_name: str,
    destination_parent_fd: int,
    destination_name: str,
    flags: int,
) -> None:
    """Invoke Darwin's directory-fd-anchored flagged atomic rename."""
    if sys.platform != "darwin":
        raise NotImplementedError("flagged atomic rename is only supported on Darwin")
    libc = ctypes.CDLL(None, use_errno=True)
    renameatx_np = libc.renameatx_np
    renameatx_np.argtypes = (
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_uint,
    )
    renameatx_np.restype = ctypes.c_int
    result = renameatx_np(
        source_parent_fd,
        os.fsencode(source_name),
        destination_parent_fd,
        os.fsencode(destination_name),
        flags,
    )
    if result != 0:
        error_number = ctypes.get_errno()
        raise OSError(error_number, os.strerror(error_number), source_name, destination_name)


def _atomic_rename_exclusive(
    source: pathlib.Path | _AnchoredPath,
    destination: pathlib.Path | _AnchoredPath,
) -> None:
    """Atomically rename without replacing any destination entry."""
    if sys.platform != "darwin":
        raise NotImplementedError("atomic no-replace install requires Darwin renamex_np")
    if isinstance(source, _AnchoredPath) and isinstance(destination, _AnchoredPath):
        _darwin_renameat(
            source.parent_fd,
            source.entry_name,
            destination.parent_fd,
            destination.entry_name,
            RENAME_EXCL,
        )
        return
    _darwin_rename(source, destination, RENAME_EXCL)


def _write_file_at(
    content: bytes,
    parent_fd: int,
    name: str,
    creation_ledger: dict[str, tuple[int, int, int]] | None = None,
    relative: pathlib.Path | None = None,
) -> None:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(name, flags, 0o600, dir_fd=parent_fd)
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode):
            raise FileExistsError(f"created release file is unsafe: {relative or name}")
        if creation_ledger is not None and relative is not None:
            creation_ledger[str(relative)] = _temporary_identity(opened)
        with os.fdopen(descriptor, "wb", closefd=False) as target:
            target.write(content)
            target.flush()
        os.fchmod(descriptor, 0o600)
    finally:
        os.close(descriptor)


def _copy_release_content(
    source_snapshot: dict[str, tuple[str, bytes | None]],
    temporary_release: pathlib.Path | _AnchoredPath,
) -> None:
    if isinstance(temporary_release, _AnchoredPath):
        owns_temporary_fd = temporary_release.directory_fd is None
        temporary_fd = temporary_release.directory_fd
        if temporary_fd is None:
            temporary_fd = os.open(
                temporary_release.entry_name,
                _DIRECTORY_OPEN_FLAGS,
                dir_fd=temporary_release.parent_fd,
            )
        try:
            directory_fds: dict[pathlib.Path, int] = {pathlib.Path(): temporary_fd}
            try:
                for raw_relative, (entry_type, _) in sorted(
                    source_snapshot.items(),
                    key=lambda item: (len(pathlib.Path(item[0]).parts), item[0]),
                ):
                    if entry_type != "directory":
                        continue
                    relative = pathlib.Path(raw_relative)
                    parent_fd = directory_fds[relative.parent]
                    os.mkdir(relative.name, 0o700, dir_fd=parent_fd)
                    created = os.stat(
                        relative.name,
                        dir_fd=parent_fd,
                        follow_symlinks=False,
                    )
                    if not stat.S_ISDIR(created.st_mode):
                        raise FileExistsError(f"created release directory is unsafe: {relative}")
                    created_identity = _temporary_identity(created)
                    temporary_release.creation_ledger[str(relative)] = created_identity
                    descriptor = os.open(
                        relative.name,
                        _DIRECTORY_OPEN_FLAGS,
                        dir_fd=parent_fd,
                    )
                    try:
                        opened = os.fstat(descriptor)
                        active = os.stat(
                            relative.name,
                            dir_fd=parent_fd,
                            follow_symlinks=False,
                        )
                    except Exception:
                        os.close(descriptor)
                        raise
                    if (
                        not stat.S_ISDIR(opened.st_mode)
                        or _temporary_identity(opened) != created_identity
                        or _temporary_identity(active) != created_identity
                    ):
                        os.close(descriptor)
                        raise FileExistsError(f"created release directory changed: {relative}")
                    directory_fds[relative] = descriptor
                for raw_relative, (entry_type, content) in source_snapshot.items():
                    if entry_type != "file":
                        continue
                    if content is None:
                        raise ValueError(f"source snapshot file has no content: {raw_relative}")
                    relative = pathlib.Path(raw_relative)
                    _write_file_at(
                        content,
                        directory_fds[relative.parent],
                        relative.name,
                        temporary_release.creation_ledger,
                        relative,
                    )
            finally:
                for relative, descriptor in reversed(list(directory_fds.items())):
                    if relative != pathlib.Path():
                        os.close(descriptor)
        finally:
            if owns_temporary_fd:
                os.close(temporary_fd)
        return
    for raw_relative, (entry_type, content) in sorted(
        source_snapshot.items(),
        key=lambda item: (len(pathlib.Path(item[0]).parts), item[0]),
    ):
        destination = temporary_release / raw_relative
        if entry_type == "directory":
            destination.mkdir(mode=0o700)
        elif content is not None:
            destination.write_bytes(content)
            destination.chmod(0o600)


def _verify_and_make_private_release(
    release: _AnchoredPath,
    expected_entries: dict[str, tuple[str, bytes | None]],
) -> None:
    try:
        directory_fd = os.open(
            release.entry_name,
            _DIRECTORY_OPEN_FLAGS,
            dir_fd=release.parent_fd,
        )
    except OSError as error:
        raise FileExistsError(f"existing release path is unsafe: {release}") from error
    try:
        opened = os.fstat(directory_fd)
        identity = opened.st_dev, opened.st_ino
        _verify_and_make_private_fd(directory_fd, expected_entries)
        try:
            active = os.stat(
                release.entry_name,
                dir_fd=release.parent_fd,
                follow_symlinks=False,
            )
        except OSError as error:
            raise FileExistsError(
                f"release {release.entry_name} changed during verification"
            ) from error
        if not stat.S_ISDIR(active.st_mode) or (active.st_dev, active.st_ino) != identity:
            raise FileExistsError(
                f"release {release.entry_name} changed during verification"
            )
    finally:
        os.close(directory_fd)


def _pin_release_entries_fd(
    directory_fd: int,
    pinned: list[tuple[int, int, str, tuple[int, int, int], bool]],
    prefix: pathlib.Path = pathlib.Path(),
) -> dict[str, tuple[str, bytes | None]]:
    entries: dict[str, tuple[str, bytes | None]] = {}
    for name in os.listdir(directory_fd):
        relative = prefix / name
        before = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        if stat.S_ISLNK(before.st_mode):
            raise FileExistsError(f"release contains a symlink: {relative}")
        if stat.S_ISDIR(before.st_mode):
            descriptor = os.open(name, _DIRECTORY_OPEN_FLAGS, dir_fd=directory_fd)
            try:
                opened = os.fstat(descriptor)
            except Exception:
                os.close(descriptor)
                raise
            if _temporary_identity(opened) != _temporary_identity(before):
                os.close(descriptor)
                raise FileExistsError(f"release directory changed while opening: {relative}")
            pinned.append(
                (descriptor, directory_fd, name, _temporary_identity(opened), True)
            )
            entries[str(relative)] = ("directory", None)
            entries.update(_pin_release_entries_fd(descriptor, pinned, relative))
        elif stat.S_ISREG(before.st_mode):
            descriptor = os.open(
                name,
                os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
                dir_fd=directory_fd,
            )
            try:
                opened = os.fstat(descriptor)
            except Exception:
                os.close(descriptor)
                raise
            if _temporary_identity(opened) != _temporary_identity(before):
                os.close(descriptor)
                raise FileExistsError(f"release file changed while opening: {relative}")
            pinned.append(
                (descriptor, directory_fd, name, _temporary_identity(opened), False)
            )
            with os.fdopen(descriptor, "rb", closefd=False) as handle:
                entries[str(relative)] = ("file", handle.read())
        else:
            raise FileExistsError(f"release contains an unsafe file: {relative}")
    return entries


def _release_entries_from_pinned_fds(
    directory_fd: int,
    pinned: list[tuple[int, int, str, tuple[int, int, int], bool]],
    prefix: pathlib.Path = pathlib.Path(),
) -> dict[str, tuple[str, bytes | None]]:
    root_metadata = os.fstat(directory_fd)
    if not stat.S_ISDIR(root_metadata.st_mode) or stat.S_IMODE(root_metadata.st_mode) != 0o700:
        raise FileExistsError(f"release directory permissions changed: {prefix or '.'}")
    children = {
        name: (descriptor, expected_identity, is_directory)
        for descriptor, parent_fd, name, expected_identity, is_directory in pinned
        if parent_fd == directory_fd
    }
    if set(os.listdir(directory_fd)) != set(children):
        raise FileExistsError(f"release directory inventory changed: {prefix or '.'}")
    entries: dict[str, tuple[str, bytes | None]] = {}
    for name, (descriptor, expected_identity, is_directory) in children.items():
        relative = prefix / name
        try:
            active = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        except OSError as error:
            raise FileExistsError(f"release entry changed after verification: {relative}") from error
        if _temporary_identity(active) != expected_identity:
            raise FileExistsError(f"release entry changed after verification: {relative}")
        opened = os.fstat(descriptor)
        expected_mode = 0o700 if is_directory else 0o600
        expected_type = stat.S_ISDIR if is_directory else stat.S_ISREG
        if (
            _temporary_identity(opened) != expected_identity
            or not expected_type(opened.st_mode)
            or stat.S_IMODE(opened.st_mode) != expected_mode
        ):
            raise FileExistsError(f"release entry permissions changed: {relative}")
        if is_directory:
            entries[str(relative)] = ("directory", None)
            entries.update(_release_entries_from_pinned_fds(descriptor, pinned, relative))
        else:
            os.lseek(descriptor, 0, os.SEEK_SET)
            with os.fdopen(descriptor, "rb", closefd=False) as handle:
                entries[str(relative)] = ("file", handle.read())
    return entries


def _verify_and_make_private_fd(
    directory_fd: int,
    expected_entries: dict[str, tuple[str, bytes | None]],
) -> None:
    pinned: list[tuple[int, int, str, tuple[int, int, int], bool]] = []
    try:
        actual_entries = _pin_release_entries_fd(directory_fd, pinned)
        if actual_entries != expected_entries:
            raise FileExistsError("release content is incomplete or inconsistent")
        os.fchmod(directory_fd, 0o700)
        for descriptor, _, _, _, is_directory in pinned:
            os.fchmod(descriptor, 0o700 if is_directory else 0o600)
        final_entries = _release_entries_from_pinned_fds(directory_fd, pinned)
        if final_entries != expected_entries:
            raise FileExistsError("release content changed while making permissions private")
    finally:
        for descriptor, _, _, _, _ in reversed(pinned):
            os.close(descriptor)


def _entry_exists(parent_fd: int, name: str) -> bool:
    try:
        os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        return True
    except FileNotFoundError:
        return False


def _temporary_identity(metadata: os.stat_result) -> tuple[int, int, int]:
    return metadata.st_dev, metadata.st_ino, stat.S_IFMT(metadata.st_mode)


def _delete_tree_contents_fd(
    directory_fd: int,
    creation_ledger: dict[str, tuple[int, int, int]],
    prefix: pathlib.Path = pathlib.Path(),
) -> None:
    children = {
        relative.name: (relative, identity)
        for raw_relative, identity in creation_ledger.items()
        for relative in (pathlib.Path(raw_relative),)
        if relative.parent == prefix
    }
    for name, (relative, expected_identity) in children.items():
        try:
            before = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        except OSError as error:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict while inspecting {relative}"
            ) from error
        if _temporary_identity(before) != expected_identity:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict while inspecting {relative}"
            )
        while True:
            quarantine_name = f".cleanup-child-{uuid.uuid4().hex}"
            try:
                _darwin_renameat(
                    directory_fd,
                    name,
                    directory_fd,
                    quarantine_name,
                    RENAME_EXCL,
                )
                break
            except FileExistsError:
                continue
            except OSError as error:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict while claiming {relative}"
                ) from error

        try:
            claimed = os.stat(
                quarantine_name,
                dir_fd=directory_fd,
                follow_symlinks=False,
            )
        except OSError as error:
            try:
                _restore_cleanup_claim(directory_fd, quarantine_name, name)
            except TemporaryCleanupConflict:
                pass
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict while inspecting claimed {relative}"
            ) from error
        if _temporary_identity(claimed) != expected_identity:
            _restore_cleanup_claim(directory_fd, quarantine_name, name)
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict; replacement preserved at {relative}"
            )

        try:
            if stat.S_ISDIR(expected_identity[2]):
                try:
                    child_fd = os.open(
                        quarantine_name,
                        _DIRECTORY_OPEN_FLAGS,
                        dir_fd=directory_fd,
                    )
                except OSError as error:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict while opening claimed {relative}"
                    ) from error
                try:
                    if _temporary_identity(os.fstat(child_fd)) != expected_identity:
                        raise TemporaryCleanupConflict(
                            f"temporary cleanup conflict while opening claimed {relative}"
                        )
                    _delete_tree_contents_fd(child_fd, creation_ledger, relative)
                finally:
                    os.close(child_fd)
                try:
                    active = os.stat(
                        quarantine_name,
                        dir_fd=directory_fd,
                        follow_symlinks=False,
                    )
                except OSError as error:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict before removing claimed {relative}"
                    ) from error
                if _temporary_identity(active) != expected_identity:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict before removing claimed {relative}"
                    )
                try:
                    os.rmdir(quarantine_name, dir_fd=directory_fd)
                except OSError as error:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict before removing claimed {relative}"
                    ) from error
            else:
                try:
                    active = os.stat(
                        quarantine_name,
                        dir_fd=directory_fd,
                        follow_symlinks=False,
                    )
                except OSError as error:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict before unlinking claimed {relative}"
                    ) from error
                if _temporary_identity(active) != expected_identity:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict before unlinking claimed {relative}"
                    )
                os.unlink(quarantine_name, dir_fd=directory_fd)
        except Exception:
            try:
                _restore_cleanup_claim(directory_fd, quarantine_name, name)
            except TemporaryCleanupConflict:
                pass
            raise


def _temporary_tree_inventory_fd(
    directory_fd: int,
    prefix: pathlib.Path = pathlib.Path(),
) -> dict[str, tuple[int, int, int]]:
    inventory: dict[str, tuple[int, int, int]] = {}
    try:
        names = os.listdir(directory_fd)
    except OSError as error:
        raise TemporaryCleanupConflict("temporary cleanup conflict while listing contents") from error
    for name in names:
        relative = prefix / name
        try:
            before = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        except OSError as error:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict while inspecting {relative}"
            ) from error
        identity = _temporary_identity(before)
        inventory[str(relative)] = identity
        if stat.S_ISDIR(before.st_mode):
            try:
                child_fd = os.open(name, _DIRECTORY_OPEN_FLAGS, dir_fd=directory_fd)
            except OSError as error:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict while opening {relative}"
                ) from error
            try:
                if _temporary_identity(os.fstat(child_fd)) != identity:
                    raise TemporaryCleanupConflict(
                        f"temporary cleanup conflict while opening {relative}"
                    )
                inventory.update(_temporary_tree_inventory_fd(child_fd, relative))
            finally:
                os.close(child_fd)
    return inventory


def _restore_cleanup_claim(parent_fd: int, quarantine_name: str, temporary_name: str) -> None:
    try:
        _darwin_renameat(
            parent_fd,
            quarantine_name,
            parent_fd,
            temporary_name,
            RENAME_EXCL,
        )
    except OSError as error:
        raise TemporaryCleanupConflict(
            f"temporary cleanup conflict; unknown entry preserved as {quarantine_name}"
        ) from error


def _cleanup_owned_temporary(
    parent_fd: int,
    temporary_name: str,
    created_identity: tuple[int, int, int],
    creation_ledger: dict[str, tuple[int, int, int]],
    directory_fd: int,
) -> None:
    while True:
        quarantine_name = f".cleanup-{uuid.uuid4().hex}"
        try:
            _darwin_renameat(
                parent_fd,
                temporary_name,
                parent_fd,
                quarantine_name,
                RENAME_EXCL,
            )
            break
        except FileExistsError:
            continue
        except OSError as error:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict; {temporary_name} could not be claimed"
            ) from error

    try:
        claimed = os.stat(quarantine_name, dir_fd=parent_fd, follow_symlinks=False)
    except OSError as error:
        raise TemporaryCleanupConflict(
            f"temporary cleanup conflict; claimed entry {quarantine_name} disappeared"
        ) from error
    if _temporary_identity(claimed) != created_identity:
        _restore_cleanup_claim(parent_fd, quarantine_name, temporary_name)
        raise TemporaryCleanupConflict(
            f"temporary cleanup conflict; unknown entry restored as {temporary_name}"
        )

    if stat.S_ISDIR(claimed.st_mode):
        try:
            if _temporary_identity(os.fstat(directory_fd)) != created_identity:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict while opening {quarantine_name}"
                )
            if _temporary_tree_inventory_fd(directory_fd) != creation_ledger:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; unknown contents preserved as {temporary_name}"
                )
            _delete_tree_contents_fd(directory_fd, creation_ledger)
            active = os.stat(quarantine_name, dir_fd=parent_fd, follow_symlinks=False)
            if _temporary_identity(active) != created_identity:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict before removing {quarantine_name}"
                )
            try:
                os.rmdir(quarantine_name, dir_fd=parent_fd)
            except OSError as error:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict before removing {quarantine_name}"
                ) from error
        except Exception:
            _restore_cleanup_claim(parent_fd, quarantine_name, temporary_name)
            raise
    else:
        try:
            active = os.stat(quarantine_name, dir_fd=parent_fd, follow_symlinks=False)
        except OSError as error:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict before unlinking {quarantine_name}"
            ) from error
        if _temporary_identity(active) != created_identity:
            raise TemporaryCleanupConflict(
                f"temporary cleanup conflict before unlinking {quarantine_name}"
            )
        os.unlink(quarantine_name, dir_fd=parent_fd)


def _managed_current_matches(install_fd: int, link_text: str) -> bool:
    try:
        metadata = os.stat("current", dir_fd=install_fd, follow_symlinks=False)
        return stat.S_ISLNK(metadata.st_mode) and os.readlink("current", dir_fd=install_fd) == link_text
    except OSError:
        return False


def _activate_release(install_root: pathlib.Path, install_fd: int, version: str) -> None:
    link_text = str(pathlib.Path("releases") / version)
    try:
        os.symlink(link_text, "current", dir_fd=install_fd)
    except FileExistsError as error:
        if not _managed_current_matches(install_fd, link_text):
            raise FileExistsError("current exists with unknown or different content") from error


def install_runtime(
    source_root: pathlib.Path | str,
    paths: RuntimePaths,
    *,
    activate: bool = True,
) -> dict[str, str]:
    """Install *source_root* as a private versioned release and activate it."""
    if sys.platform != "darwin":
        raise NotImplementedError("runtime installation requires Darwin atomic rename support")
    source = pathlib.Path(source_root)
    expected_entries = _snapshot_source_release(source)
    manifest_content = expected_entries["release.json"][1]
    if manifest_content is None:
        raise ValueError("release manifest snapshot is missing content")
    manifest = json.loads(manifest_content.decode("utf-8"))
    if not isinstance(manifest, dict):
        raise ValueError("release manifest must contain a JSON object")
    version = _validate_manifest(manifest)
    install_root, install_fd, releases, releases_fd = _open_install_layout(paths)
    try:
        destination = _AnchoredPath(releases_fd, version, releases / version)
        if _entry_exists(releases_fd, version):
            _verify_and_make_private_release(destination, expected_entries)
            if activate:
                _activate_release(install_root, install_fd, version)
            return {"version": version}

        while True:
            temporary_name = f".{version}.tmp-{uuid.uuid4().hex}"
            try:
                os.mkdir(temporary_name, 0o700, dir_fd=releases_fd)
                break
            except FileExistsError:
                continue
        temporary_release = _AnchoredPath(
            releases_fd,
            temporary_name,
            releases / temporary_name,
        )
        temporary_fd: int | None = None
        temporary_identity: tuple[int, int, int] | None = None
        published = False
        try:
            temporary_fd = os.open(temporary_name, _DIRECTORY_OPEN_FLAGS, dir_fd=releases_fd)
            try:
                opened_temporary = os.fstat(temporary_fd)
            except Exception as error:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} ownership could not be established"
                ) from error
            if (
                not stat.S_ISDIR(opened_temporary.st_mode)
                or stat.S_IMODE(opened_temporary.st_mode) != 0o700
            ):
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} is not the created empty directory"
                )
            temporary_identity = _temporary_identity(opened_temporary)
            if os.listdir(temporary_fd):
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} is not the created empty directory"
                )
            temporary_release.directory_fd = temporary_fd
            _copy_release_content(expected_entries, temporary_release)
            try:
                _verify_and_make_private_fd(temporary_fd, expected_entries)
            except FileExistsError as error:
                raise ValueError("copied release content is incomplete or inconsistent") from error
            try:
                active_before_publish = os.stat(
                    temporary_name,
                    dir_fd=releases_fd,
                    follow_symlinks=False,
                )
            except OSError as error:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} changed before publication"
                ) from error
            if _temporary_identity(active_before_publish) != temporary_identity:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} changed before publication"
                )
            try:
                _atomic_rename_exclusive(temporary_release, destination)
                published = True
            except FileExistsError as error:
                try:
                    _verify_and_make_private_release(destination, expected_entries)
                except FileExistsError as conflict:
                    raise conflict from error
            try:
                active_temporary = os.stat(
                    temporary_name,
                    dir_fd=releases_fd,
                    follow_symlinks=False,
                )
            except FileNotFoundError:
                active_temporary = None
            if not published and (
                active_temporary is None
                or _temporary_identity(active_temporary) != temporary_identity
            ):
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} changed before publication"
                )
        except TemporaryCleanupConflict:
            raise
        except Exception as error:
            if temporary_fd is None:
                raise TemporaryCleanupConflict(
                    f"temporary cleanup conflict; {temporary_name} could not be opened safely"
                ) from error
            raise
        finally:
            if temporary_fd is not None:
                try:
                    if not published and temporary_identity is not None:
                        _cleanup_owned_temporary(
                            releases_fd,
                            temporary_name,
                            temporary_identity,
                            temporary_release.creation_ledger,
                            temporary_fd,
                        )
                finally:
                    os.close(temporary_fd)

        if activate:
            _activate_release(install_root, install_fd, version)
        return {"version": version}
    finally:
        os.close(releases_fd)
        os.close(install_fd)


def validate_runtime_source(source_root: pathlib.Path | str) -> dict[str, str]:
    """Fully validate a release source without creating or activating anything."""
    expected_entries = _snapshot_source_release(pathlib.Path(source_root))
    manifest_content = expected_entries["release.json"][1]
    if manifest_content is None:
        raise ValueError("release manifest snapshot is missing content")
    manifest = json.loads(manifest_content.decode("utf-8"))
    if not isinstance(manifest, dict):
        raise ValueError("release manifest must contain a JSON object")
    return {"version": _validate_manifest(manifest)}


def _read_launch_agent_template() -> str:
    return _LAUNCH_AGENT_TEMPLATE.read_text(encoding="utf-8")


def _validate_launch_agent(plist: object, runtime: str, port: int) -> None:
    if not isinstance(plist, dict):
        raise ValueError("launch agent template must contain a dictionary")
    python_executable = plist.get("ProgramArguments", [None])[0] if isinstance(plist, dict) else None
    if not isinstance(python_executable, str):
        raise ValueError("launch agent ProgramArguments are invalid")
    expected_arguments = [python_executable, runtime + "/scripts/memory_review_server.py"]
    try:
        validate_python(python_executable)
    except InstallError as error:
        raise ValueError("launch agent Python interpreter is invalid") from error
    expected_environment = {
        "MEMORY_REVIEW_HOST": "127.0.0.1",
        "MEMORY_REVIEW_PORT": str(port),
    }
    if plist.get("Label") != "com.noema.vibe-memory":
        raise ValueError("launch agent Label is invalid")
    if plist.get("ProgramArguments") != expected_arguments:
        raise ValueError("launch agent ProgramArguments are invalid")
    if plist.get("EnvironmentVariables") != expected_environment:
        raise ValueError("launch agent environment is invalid")
    if plist.get("KeepAlive") is not True or plist.get("RunAtLoad") is not True:
        raise ValueError("launch agent lifecycle settings are invalid")


def _python_metadata(
    executable: str | os.PathLike[str],
    probe: Callable[[str], tuple[int, int] | None] = probe_python,
) -> tuple[str, str]:
    validated = validate_python(executable, probe)
    version = probe(validated)
    if version is None:
        raise InstallError("Python 3.10 or newer is required")
    return validated, f"{version[0]}.{version[1]}"


def _runtime_python(paths: RuntimePaths) -> str:
    try:
        value = read_runtime_config(paths)
        persisted = value.get("python_executable")
        if isinstance(persisted, str):
            return _python_metadata(persisted)[0]
    except (InstallError, OSError, ValueError):
        pass
    return discover_python()


def render_launch_agent(
    paths: RuntimePaths,
    port: int = 8897,
    *,
    python_executable: str | os.PathLike[str] | None = None,
) -> str:
    """Render and validate the loopback-only LaunchAgent property list."""
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError("port must be an integer from 1 through 65535")
    runtime = str(pathlib.Path(paths.install_root) / "current")
    python = _python_metadata(python_executable)[0] if python_executable is not None else _runtime_python(paths)
    rendered = Template(_read_launch_agent_template()).substitute(
        PYTHON=escape(python),
        RUNTIME=escape(runtime),
        PORT=str(port),
    )
    try:
        plist = plistlib.loads(rendered.encode("utf-8"))
    except Exception as error:
        raise ValueError("rendered launch agent is not a valid plist") from error
    _validate_launch_agent(plist, runtime, port)
    return rendered


def render_runtime_config(
    port: int,
    app_version: str,
    *,
    python_executable: str | os.PathLike[str] | None = None,
) -> str:
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError("port must be an integer from 1 through 65535")
    if not isinstance(app_version, str) or not _VERSION_PATTERN.fullmatch(app_version):
        raise ValueError("app_version must be a semantic version")
    executable, python_version = _python_metadata(
        python_executable if python_executable is not None else discover_python()
    )
    return json.dumps(
        {
            "app_version": app_version,
            "port": port,
            "python_executable": executable,
            "python_version": python_version,
            "schema_version": 1,
            "service": "vibe-memory",
        },
        indent=2,
        sort_keys=True,
    ) + "\n"


def _shell_double_quote(value: str) -> str:
    """Quote one shell word without embedding an untrusted shell expression."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`") + '"'


def render_launcher(
    paths: RuntimePaths,
    *,
    python_executable: str | os.PathLike[str] | None = None,
) -> str:
    """Render the user-owned stable CLI launcher for the active runtime."""
    executable = (
        _python_metadata(python_executable)[0]
        if python_executable is not None
        else _runtime_python(paths)
    )
    return "\n".join(
        (
            "#!/usr/bin/env bash",
            LAUNCHER_MARKER,
            "set -euo pipefail",
            'if [ -z "${HOME:-}" ]; then',
            '  echo "vibe-memory: HOME is required" >&2',
            "  exit 1",
            "fi",
            'RUNTIME="$HOME/Library/Application Support/VibeMemory/current"',
            f"exec {_shell_double_quote(executable)} \"$RUNTIME/scripts/vibe_memory_cli.py\" \"$@\"",
            "",
        )
    )


def _is_manager_launcher(content: bytes) -> bool:
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return (
        text.startswith(f"#!/usr/bin/env bash\n{LAUNCHER_MARKER}\n")
        and 'RUNTIME="$HOME/Library/Application Support/VibeMemory/current"' in text
        and "\nexec " in text
    )


def _launcher_snapshot(
    parent_fd: int,
    target: pathlib.Path,
) -> tuple[tuple[int, int], bytes, int] | None:
    """Return a no-follow launcher snapshot for a final promotion comparison."""
    if not _entry_exists(parent_fd, target.name):
        return None
    try:
        before = os.stat(target.name, dir_fd=parent_fd, follow_symlinks=False)
    except OSError as error:
        raise InstallError("launcher target changed while reading") from error
    if not stat.S_ISREG(before.st_mode):
        raise InstallError("launcher target must be a regular file")
    current = _read_regular_file_at(parent_fd, target.name, target)
    try:
        after = os.stat(target.name, dir_fd=parent_fd, follow_symlinks=False)
    except OSError as error:
        raise InstallError("launcher target changed while reading") from error
    if not stat.S_ISREG(after.st_mode) or _identity(after) != _identity(before):
        raise InstallError("launcher target changed while reading")
    return _identity(after), current, stat.S_IMODE(after.st_mode)


def install_runtime_config(
    paths: RuntimePaths,
    *,
    port: int,
    app_version: str,
    python_executable: str | os.PathLike[str] | None = None,
) -> dict[str, object]:
    selected_python = python_executable
    if selected_python is None:
        try:
            selected_python = read_runtime_config(paths).get("python_executable")
        except (InstallError, OSError, ValueError):
            selected_python = None
    runtime_value = json.loads(
        render_runtime_config(
            port,
            app_version,
            python_executable=selected_python,
        )
    )
    content = (json.dumps(runtime_value, indent=2, sort_keys=True) + "\n").encode("utf-8")
    parent = pathlib.Path(paths.install_root)
    _validate_install_ancestor_chain(parent)
    parent_fd = _open_or_create_directory_chain(_canonical_install_path(parent))
    name = "config.json"
    target = parent / name
    try:
        if _entry_exists(parent_fd, name):
            current = _read_regular_file_at(parent_fd, name, target)
            try:
                current_value = json.loads(current.decode("utf-8"))
                import vibe_memory_settings

                settings_keys = set(vibe_memory_settings.default_settings())
                if isinstance(current_value, dict) and settings_keys.issubset(current_value):
                    preserved_settings = {
                        key: current_value[key] for key in settings_keys
                    }
                    vibe_memory_settings.validate_settings(preserved_settings)
                    preserved_settings["service_port"] = port
                    combined = {**runtime_value, **preserved_settings}
                    content = (
                        json.dumps(combined, indent=2, sort_keys=True) + "\n"
                    ).encode("utf-8")
            except (UnicodeDecodeError, json.JSONDecodeError, ValueError):
                pass
            if current == content:
                return {
                    "changed": False,
                    "path": str(target),
                    "python_executable": runtime_value["python_executable"],
                }
        temporary_name = f".{name}.tmp-{uuid.uuid4().hex}"
        descriptor = os.open(
            temporary_name,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            0o600,
            dir_fd=parent_fd,
        )
        try:
            offset = 0
            while offset < len(content):
                written = os.write(descriptor, content[offset:])
                if written <= 0:
                    raise OSError("short runtime config write")
                offset += written
            os.fchmod(descriptor, 0o600)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        try:
            if _entry_exists(parent_fd, name):
                metadata = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
                if not stat.S_ISREG(metadata.st_mode):
                    raise ValueError("runtime config target must be a regular file")
            os.replace(temporary_name, name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
            os.fsync(parent_fd)
        finally:
            try:
                os.unlink(temporary_name, dir_fd=parent_fd)
            except FileNotFoundError:
                pass
        return {
            "changed": True,
            "path": str(target),
            "python_executable": runtime_value["python_executable"],
        }
    finally:
        os.close(parent_fd)


def install_launcher(
    paths: RuntimePaths,
    *,
    python_executable: str | os.PathLike[str] | None = None,
) -> dict[str, object]:
    """Atomically install the private, stable user CLI launcher."""
    target = pathlib.Path(paths.launcher)
    content = render_launcher(paths, python_executable=python_executable).encode("utf-8")
    _validate_install_ancestor_chain(target.parent)
    parent_fd = _open_or_create_directory_chain(_canonical_install_path(target.parent))
    temporary_name = f".{target.name}.tmp-{uuid.uuid4().hex}"
    try:
        initial = _launcher_snapshot(parent_fd, target)
        if initial is not None:
            _initial_identity, current, current_mode = initial
            if not _is_manager_launcher(current):
                raise InstallError("launcher target is not manager-owned")
            if current == content and current_mode == 0o700:
                return {"changed": False, "path": str(target)}
        descriptor = os.open(
            temporary_name,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            0o700,
            dir_fd=parent_fd,
        )
        try:
            offset = 0
            while offset < len(content):
                written = os.write(descriptor, content[offset:])
                if written <= 0:
                    raise OSError("short launcher write")
                offset += written
            os.fchmod(descriptor, 0o700)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        final = _launcher_snapshot(parent_fd, target)
        if initial is None:
            if final is not None:
                raise InstallError("launcher target appeared during installation")
        else:
            if (
                final is None
                or final[0] != initial[0]
                or final[1] != initial[1]
                or not _is_manager_launcher(final[1])
            ):
                raise InstallError("launcher target changed during installation")
        os.replace(temporary_name, target.name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        os.fsync(parent_fd)
        return {"changed": True, "path": str(target)}
    finally:
        try:
            os.unlink(temporary_name, dir_fd=parent_fd)
        except FileNotFoundError:
            pass
        os.close(parent_fd)


def _read_runtime_config_document(paths: RuntimePaths) -> dict[str, object]:
    """Read a runtime config from a regular file without following symlinks."""
    target = pathlib.Path(paths.install_root) / "config.json"
    _validate_install_ancestor_chain(target.parent)
    canonical_parent = _canonical_install_path(target.parent)
    parent_fd = os.open(canonical_parent, _DIRECTORY_OPEN_FLAGS)
    try:
        raw = _read_regular_file_at(parent_fd, target.name, target)
    finally:
        os.close(parent_fd)
    value = json.loads(raw.decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("runtime config must contain an object")
    return value


def read_runtime_config(paths: RuntimePaths) -> dict[str, object]:
    value = _read_runtime_config_document(paths)
    runtime_keys = {
        "app_version",
        "port",
        "python_executable",
        "python_version",
        "schema_version",
        "service",
    }
    runtime_value = {key: value.get(key) for key in runtime_keys}
    legacy_runtime = runtime_value["python_executable"] is None and runtime_value["python_version"] is None
    if (runtime_value["python_executable"] is None) != (runtime_value["python_version"] is None):
        raise ValueError("runtime config has an invalid Python interpreter structure")
    expected = json.loads(
        render_runtime_config(
            runtime_value.get("port"),
            runtime_value.get("app_version"),
            python_executable=(
                runtime_value["python_executable"] if not legacy_runtime else discover_python()
            ),
        )
    )
    normalized = {
        key: expected[key]
        for key in runtime_keys
        if key in expected and (key not in {"python_executable", "python_version"} or not legacy_runtime)
    }
    compared = {
        key: runtime_value[key]
        for key in normalized
    }
    if compared != normalized:
        raise ValueError("runtime config has an invalid structure")
    extra = set(value).difference(runtime_keys)
    if extra:
        import vibe_memory_settings

        settings_keys = set(vibe_memory_settings.default_settings())
        if extra != settings_keys.difference({"schema_version"}):
            raise ValueError("runtime config has an invalid structure")
        settings_value = {
            key: value[key] if key in value else value["schema_version"]
            for key in settings_keys
        }
        vibe_memory_settings.validate_settings(settings_value)
        if settings_value["service_port"] != runtime_value["port"]:
            raise ValueError("runtime config ports do not match")
    return value


def install_launch_agent(paths: RuntimePaths, content: str) -> dict[str, object]:
    """Atomically install the managed LaunchAgent without following symlinks."""
    target = pathlib.Path(paths.launch_agent)
    parent = target.parent
    _validate_install_ancestor_chain(parent)
    canonical_parent = _canonical_install_path(parent)
    parent_fd = _open_or_create_directory_chain(canonical_parent)
    name = "com.noema.vibe-memory.plist"
    encoded = content.encode("utf-8")
    try:
        if _entry_exists(parent_fd, name):
            current = _read_regular_file_at(parent_fd, name, target)
            if current == encoded:
                return {"changed": False, "path": str(target)}
        temporary_name = f".{name}.tmp-{uuid.uuid4().hex}"
        descriptor = os.open(
            temporary_name,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            0o600,
            dir_fd=parent_fd,
        )
        try:
            os.fchmod(descriptor, 0o600)
            offset = 0
            while offset < len(encoded):
                written = os.write(descriptor, encoded[offset:])
                if written <= 0:
                    raise OSError("short LaunchAgent write")
                offset += written
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        try:
            if _entry_exists(parent_fd, name):
                metadata = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
                if not stat.S_ISREG(metadata.st_mode):
                    raise ValueError("LaunchAgent target must be a regular file")
            os.replace(
                temporary_name,
                name,
                src_dir_fd=parent_fd,
                dst_dir_fd=parent_fd,
            )
            os.fsync(parent_fd)
        finally:
            try:
                os.unlink(temporary_name, dir_fd=parent_fd)
            except FileNotFoundError:
                pass
        return {"changed": True, "path": str(target)}
    finally:
        os.close(parent_fd)


def _ensure_private_data_file(path: pathlib.Path, content: str) -> dict[str, str]:
    _validate_install_ancestor_chain(path.parent)
    parent_fd = _open_or_create_directory_chain(_canonical_install_path(path.parent))
    try:
        if _entry_exists(parent_fd, path.name):
            metadata = os.stat(path.name, dir_fd=parent_fd, follow_symlinks=False)
            if not stat.S_ISREG(metadata.st_mode):
                raise ValueError(f"managed data path must be a regular file: {path}")
            descriptor = os.open(
                path.name,
                os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
                dir_fd=parent_fd,
            )
            try:
                os.fchmod(descriptor, 0o600)
                os.fsync(descriptor)
            finally:
                os.close(descriptor)
            return {"path": str(path), "status": "existing"}
        _write_file_at(content.encode("utf-8"), parent_fd, path.name)
        descriptor = os.open(
            path.name,
            os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
            dir_fd=parent_fd,
        )
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        os.fsync(parent_fd)
        return {"path": str(path), "status": "created"}
    finally:
        os.close(parent_fd)


def prepare_data(paths: RuntimePaths) -> dict[str, list[dict[str, str]]]:
    """Create only missing private data roots and empty governance files."""
    defaults = (
        (paths.personal_memory / "long.md", "# Personal Codex Long Memory\n"),
        (paths.personal_memory / "short.md", "# Personal Codex Short Memory\n"),
        (paths.personal_memory / "proposals.md", "# Personal Memory Proposals\n"),
        (
            paths.project_registry,
            json.dumps({"current_project": "", "projects": []}, indent=2, sort_keys=True) + "\n",
        ),
    )
    return {"files": [_ensure_private_data_file(path, content) for path, content in defaults]}


def install_state_path(paths: RuntimePaths) -> pathlib.Path:
    return pathlib.Path(paths.install_root) / "state" / "install.json"


def _atomic_write_private_json(path: pathlib.Path, value: dict[str, Any]) -> None:
    content = (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")
    parent = pathlib.Path(path.parent)
    _validate_install_ancestor_chain(parent)
    parent_fd = _open_or_create_directory_chain(_canonical_install_path(parent))
    temporary_name = f".{path.name}.tmp-{uuid.uuid4().hex}"
    try:
        descriptor = os.open(
            temporary_name,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            0o600,
            dir_fd=parent_fd,
        )
        try:
            offset = 0
            while offset < len(content):
                written = os.write(descriptor, content[offset:])
                if written <= 0:
                    raise OSError("short private JSON write")
                offset += written
            os.fchmod(descriptor, 0o600)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        if _entry_exists(parent_fd, path.name):
            metadata = os.stat(path.name, dir_fd=parent_fd, follow_symlinks=False)
            if not stat.S_ISREG(metadata.st_mode):
                raise InstallError(f"managed JSON target must be a regular file: {path}")
        os.replace(
            temporary_name,
            path.name,
            src_dir_fd=parent_fd,
            dst_dir_fd=parent_fd,
        )
        os.fsync(parent_fd)
    finally:
        try:
            os.unlink(temporary_name, dir_fd=parent_fd)
        except FileNotFoundError:
            pass
        os.close(parent_fd)


def _validate_install_state(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise InstallError("install state must be an object")
    if not value:
        return {}
    required = {
        "schema_version",
        "current_version",
        "previous_version",
        "hook_protocol_version",
        "data_schema_version",
        "port",
        "installed_clients",
    }
    optional_python = {"python_executable", "python_version"}
    keys = set(value)
    if not required.issubset(keys) or keys.difference(required | optional_python):
        raise InstallError("install state has an invalid structure")
    present_python_fields = keys & optional_python
    if present_python_fields and present_python_fields != optional_python:
        raise InstallError("install state has an invalid Python structure")
    schema_version = value["schema_version"]
    if (
        isinstance(schema_version, bool)
        or not isinstance(schema_version, int)
        or schema_version != 1
    ):
        raise InstallError("install state schema version is invalid")
    for key in ("hook_protocol_version", "data_schema_version"):
        item = value[key]
        if isinstance(item, bool) or not isinstance(item, int) or item < 1:
            raise InstallError("install state has an invalid structure")
    current_version = value["current_version"]
    if not isinstance(current_version, str) or not _VERSION_PATTERN.fullmatch(current_version):
        raise InstallError("install state has an invalid current version")
    previous_version = value["previous_version"]
    if previous_version is not None and (
        not isinstance(previous_version, str) or not _VERSION_PATTERN.fullmatch(previous_version)
    ):
        raise InstallError("install state has an invalid previous version")
    port = value["port"]
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise InstallError("install state has an invalid port")
    clients = value["installed_clients"]
    if (
        not isinstance(clients, list)
        or not clients
        or any(
            not isinstance(client, str) or client not in {"codex", "claude-code"}
            for client in clients
        )
        or len(clients) != len(set(clients))
    ):
        raise InstallError("install state has invalid installed clients")
    if optional_python.issubset(keys):
        executable = value["python_executable"]
        version = value["python_version"]
        if (
            not isinstance(executable, str)
            or not executable
            or not isinstance(version, str)
            or not _PYTHON_VERSION_PATTERN.fullmatch(version)
        ):
            raise InstallError("install state has an invalid Python structure")
    return value


def read_install_state(paths: RuntimePaths) -> dict[str, Any]:
    path = install_state_path(paths)
    try:
        _validate_install_ancestor_chain(path.parent)
        parent_fd = os.open(_canonical_install_path(path.parent), _DIRECTORY_OPEN_FLAGS)
    except FileNotFoundError:
        return {}
    except (OSError, ValueError) as error:
        raise InstallError("install state is unreadable") from error
    try:
        if not _entry_exists(parent_fd, path.name):
            return {}
        raw = _read_regular_file_at(parent_fd, path.name, path)
    except (OSError, ValueError) as error:
        raise InstallError("install state is unreadable") from error
    finally:
        os.close(parent_fd)
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise InstallError("install state is malformed") from error
    return _validate_install_state(value)


def write_install_state(paths: RuntimePaths, value: dict[str, Any]) -> None:
    _atomic_write_private_json(install_state_path(paths), value)


def _current_version(paths: RuntimePaths) -> str | None:
    current = pathlib.Path(paths.install_root) / "current"
    try:
        metadata = current.lstat()
    except FileNotFoundError:
        return None
    if not stat.S_ISLNK(metadata.st_mode):
        raise InstallError("current runtime must be a managed symlink")
    link = os.readlink(current)
    prefix = "releases/"
    if not link.startswith(prefix) or pathlib.PurePosixPath(link).name != link[len(prefix):]:
        raise InstallError("current runtime symlink is not managed")
    return link[len(prefix):]


def _activate_managed_version(paths: RuntimePaths, version: str) -> None:
    if not isinstance(version, str) or not _VERSION_PATTERN.fullmatch(version):
        raise InstallError("rollback version must be a semantic version")
    release = pathlib.Path(paths.install_root) / "releases" / version
    if not release.is_dir() or release.is_symlink():
        raise InstallError(f"release is not installed: {version}")
    install_root = pathlib.Path(paths.install_root)
    _validate_install_ancestor_chain(install_root)
    install_fd = _open_or_create_directory_chain(_canonical_install_path(install_root))
    temporary_name = f".current.tmp-{uuid.uuid4().hex}"
    try:
        os.symlink(f"releases/{version}", temporary_name, dir_fd=install_fd)
        if _entry_exists(install_fd, "current"):
            metadata = os.stat("current", dir_fd=install_fd, follow_symlinks=False)
            if not stat.S_ISLNK(metadata.st_mode):
                raise InstallError("current runtime target is not a symlink")
        os.replace(
            temporary_name,
            "current",
            src_dir_fd=install_fd,
            dst_dir_fd=install_fd,
        )
        os.fsync(install_fd)
    finally:
        try:
            os.unlink(temporary_name, dir_fd=install_fd)
        except FileNotFoundError:
            pass
        os.close(install_fd)


def _read_registry_snapshot(paths: RuntimePaths) -> dict[str, object]:
    try:
        value = json.loads(paths.project_registry.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {"current_project": "", "projects": []}
    if not isinstance(value, dict):
        raise InstallError("project registry must be an object")
    value.setdefault("current_project", "")
    value.setdefault("projects", [])
    return value


def _validate_control_plane(
    paths: RuntimePaths,
    validation: dict[str, str] | None,
) -> dict[str, str]:
    if validation is not None:
        result = dict(validation)
    else:
        import vibe_memory_migration

        result = vibe_memory_migration.validate_control_plane(
            paths,
            _read_registry_snapshot(paths),
        )
    if any(status != "ok" for status in result.values()):
        raise InstallError("control-plane compatibility validation failed")
    return result


def _runtime_port(paths: RuntimePaths, explicit_port: int | None) -> int:
    if explicit_port is not None:
        if isinstance(explicit_port, bool) or not 1 <= explicit_port <= 65535:
            raise InstallError("port must be an integer from 1 through 65535")
        return explicit_port
    try:
        return int(read_runtime_config(paths)["port"])
    except Exception:
        return 8897


def _snapshot_regular_file(path: pathlib.Path) -> tuple[bytes, int] | None:
    if path.is_symlink():
        raise InstallError(f"managed file must not be a symlink: {path}")
    try:
        metadata = path.stat()
    except FileNotFoundError:
        return None
    if not stat.S_ISREG(metadata.st_mode):
        raise InstallError(f"managed file must be regular: {path}")
    return path.read_bytes(), stat.S_IMODE(metadata.st_mode)


def _restore_regular_file(path: pathlib.Path, snapshot: tuple[bytes, int] | None) -> None:
    if path.is_symlink():
        raise InstallError(f"managed file changed to symlink: {path}")
    if snapshot is None:
        try:
            metadata = path.stat()
        except FileNotFoundError:
            return
        if not stat.S_ISREG(metadata.st_mode):
            raise InstallError(f"managed file changed type: {path}")
        path.unlink()
        return
    content, mode = snapshot
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.restore-{uuid.uuid4().hex}")
    try:
        temporary.write_bytes(content)
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _install_state_document(
    *,
    current_version: str,
    previous_version: str | None,
    port: int,
    installed_clients: list[str],
    python_executable: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    executable, python_version = _python_metadata(
        python_executable if python_executable is not None else discover_python()
    )
    return {
        "schema_version": 1,
        "current_version": current_version,
        "previous_version": previous_version,
        "hook_protocol_version": 1,
        "data_schema_version": 1,
        "port": port,
        "python_executable": executable,
        "python_version": python_version,
        "installed_clients": installed_clients,
    }


def update(
    source_root: pathlib.Path | str,
    paths: RuntimePaths,
    *,
    port: int | None = None,
    installed_clients: list[str] | None = None,
    validation: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Install a new runtime release, validate it, then switch current."""
    previous_version = _current_version(paths)
    runtime_config = pathlib.Path(paths.install_root) / "config.json"
    config_before = _snapshot_regular_file(runtime_config)
    selected_port = _runtime_port(paths, port)
    selected_python = _runtime_python(paths)
    try:
        installed = install_runtime(source_root, paths, activate=False)
        new_version = installed["version"]
        install_runtime_config(
            paths,
            port=selected_port,
            app_version=new_version,
            python_executable=selected_python,
        )
        install_launcher(paths, python_executable=selected_python)
        control_plane = _validate_control_plane(paths, validation)
        _activate_managed_version(paths, new_version)
        clients = installed_clients
        if clients is None:
            state = read_install_state(paths)
            clients = [
                item
                for item in state.get("installed_clients", ["codex"])
                if item in {"codex", "claude-code"}
            ]
        if not clients:
            clients = ["codex"]
        write_install_state(
            paths,
            _install_state_document(
                current_version=new_version,
                previous_version=previous_version,
                port=selected_port,
                installed_clients=clients,
                python_executable=selected_python,
            ),
        )
        return {
            "status": "updated",
            "current_version": new_version,
            "previous_version": previous_version,
            "control_plane": control_plane,
        }
    except Exception as error:
        _restore_regular_file(runtime_config, config_before)
        if previous_version is not None:
            _activate_managed_version(paths, previous_version)
        if isinstance(error, InstallError):
            raise
        raise InstallError("update failed") from error


def rollback(paths: RuntimePaths) -> dict[str, Any]:
    """Switch current back to the previous runtime without touching memory data."""
    state = read_install_state(paths)
    previous_version = state.get("previous_version")
    if not isinstance(previous_version, str) or not previous_version:
        raise InstallError("no previous runtime version is recorded")
    current_version = _current_version(paths) or state.get("current_version")
    _activate_managed_version(paths, previous_version)
    port = int(state.get("port", 8897))
    clients = [
        item
        for item in state.get("installed_clients", ["codex"])
        if item in {"codex", "claude-code"}
    ] or ["codex"]
    write_install_state(
        paths,
        _install_state_document(
            current_version=previous_version,
            previous_version=current_version if isinstance(current_version, str) else None,
            port=port,
            installed_clients=clients,
            python_executable=state.get("python_executable") if isinstance(state.get("python_executable"), str) else _runtime_python(paths),
        ),
    )
    return {
        "status": "rolled_back",
        "current_version": previous_version,
        "previous_version": current_version,
        "data_retained": True,
    }


def _installed_clients(paths: RuntimePaths) -> list[str]:
    state = read_install_state(paths)
    clients = [
        item
        for item in state.get("installed_clients", ["codex"])
        if item in {"codex", "claude-code"}
    ]
    return clients or ["codex"]


def _hook_target_for_client(paths: RuntimePaths, client: str) -> tuple[pathlib.Path, str, str]:
    home = pathlib.Path(paths.personal_memory).parents[1]
    if client == "claude-code":
        return home / ".claude" / "settings.json", "claude-code", "claude"
    return home / ".codex" / "hooks.json", "codex", "codex"


def repair(paths: RuntimePaths) -> dict[str, Any]:
    """Re-render managed LaunchAgent and hook entries for the current runtime."""
    import vibe_memory_hooks

    runtime = pathlib.Path(paths.install_root) / "current"
    if not runtime.is_symlink():
        raise InstallError("current runtime is not installed")
    port = int(read_runtime_config(paths)["port"])
    launcher = install_launcher(paths)
    launch_agent = install_launch_agent(paths, render_launch_agent(paths, port=port))
    hook_results = {}
    for path, agent, label in (_hook_target_for_client(paths, client) for client in _installed_clients(paths)):
        hook_results[label] = vibe_memory_hooks.repair(path, agent, paths.launcher)
    return {
        "status": "repaired",
        "launch_agent": launch_agent,
        "launcher": launcher,
        "hooks": hook_results,
        "data_retained": True,
    }


def _is_managed_launch_agent(path: pathlib.Path) -> bool:
    if not path.exists():
        return False
    if path.is_symlink():
        raise InstallError(f"managed LaunchAgent must not be a symlink: {path}")
    text = path.read_text(encoding="utf-8")
    return "com.noema.vibe-memory" in text and "memory_review_server.py" in text


def _is_managed_launcher(path: pathlib.Path) -> bool:
    if not path.exists():
        return False
    if path.is_symlink():
        raise InstallError(f"managed launcher must not be a symlink: {path}")
    if not path.is_file():
        raise InstallError(f"managed launcher must be a regular file: {path}")
    return "Vibe Memory stable launcher; generated by the installer." in path.read_text(
        encoding="utf-8"
    )


def _unlink_regular_file(path: pathlib.Path) -> bool:
    if not path.exists():
        return False
    if path.is_symlink():
        raise InstallError(f"managed path must not be a symlink: {path}")
    if not path.is_file():
        raise InstallError(f"managed path must be a regular file: {path}")
    path.unlink()
    return True


def _remove_explicit_data_path(path: pathlib.Path, allowed: set[pathlib.Path]) -> None:
    resolved = path.expanduser().resolve()
    if resolved not in allowed:
        raise InstallError(f"data deletion path is not an approved managed path: {resolved}")
    if not resolved.exists():
        return
    if resolved.is_symlink():
        raise InstallError(f"data deletion refuses symlink: {resolved}")
    if resolved.is_dir():
        shutil.rmtree(resolved)
    else:
        resolved.unlink()


def uninstall(
    paths: RuntimePaths,
    *,
    remove_data: bool = False,
    approved_data_deletion: bool = False,
    data_paths: list[pathlib.Path] | None = None,
) -> dict[str, Any]:
    """Remove only managed runtime assets; retain memory data unless explicitly approved."""
    if remove_data and (not approved_data_deletion or not data_paths):
        raise InstallError(
            "data deletion requires --approved-data-deletion and explicit managed data paths"
        )
    import vibe_memory_hooks

    removed: list[str] = []
    hook_results = {}
    for client in ("codex", "claude-code"):
        path, _agent, label = _hook_target_for_client(paths, client)
        hook_results[label] = vibe_memory_hooks.uninstall(path)
    home = pathlib.Path(paths.personal_memory).parents[1]
    launch_agent = pathlib.Path(paths.launch_agent)
    if _is_managed_launch_agent(launch_agent):
        launch_agent.unlink()
        removed.append(str(launch_agent))
    launcher = pathlib.Path(paths.launcher)
    if _is_managed_launcher(launcher):
        launcher.unlink()
        removed.append(str(launcher))
    current = pathlib.Path(paths.install_root) / "current"
    if os.path.lexists(current):
        if not current.is_symlink():
            raise InstallError("current runtime target is not a managed symlink")
        current.unlink()
        removed.append(str(current))
    for path in (pathlib.Path(paths.install_root) / "config.json", install_state_path(paths)):
        if _unlink_regular_file(path):
            removed.append(str(path))
    deleted_data: list[str] = []
    if remove_data:
        allowed = {
            pathlib.Path(paths.personal_memory).resolve(),
            pathlib.Path(paths.project_registry).resolve(),
            pathlib.Path(paths.ui_design_home).resolve(),
            pathlib.Path(paths.worktree_manager).resolve(),
        }
        for raw_path in data_paths or []:
            _remove_explicit_data_path(pathlib.Path(raw_path), allowed)
            deleted_data.append(str(pathlib.Path(raw_path).expanduser().resolve()))
    return {
        "status": "uninstalled",
        "removed": removed,
        "hooks": hook_results,
        "data_retained": not remove_data,
        "deleted_data": deleted_data,
    }
